"""Yarn Classic and pnpm v9 deterministic evidence tests."""

from __future__ import annotations

import json
import shutil
from pathlib import Path

import pytest

from dependabot_validator_grunt.npm import collect_npm_evidence
from dependabot_validator_grunt.workflow import WorkflowError, triage_offline_fixture

ROOT = Path(__file__).parents[1]
CASES = ROOT / "examples" / "offline-cases"


def test_yarn_classic_direct_instance_is_positive_partial_evidence(tmp_path: Path) -> None:
    (tmp_path / "package.json").write_text(
        json.dumps({"dependencies": {"jspdf": "^2.5.1"}}),
        encoding="utf-8",
    )
    (tmp_path / "yarn.lock").write_text(
        """# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1

jspdf@^2.5.1:
  version "2.5.1"
  resolved "https://registry.yarnpkg.com/jspdf/-/jspdf-2.5.1.tgz"
  dependencies:
    fflate "^0.4.8"

fflate@^0.4.8:
  version "0.4.8"
  resolved "https://registry.yarnpkg.com/fflate/-/fflate-0.4.8.tgz"
""",
        encoding="utf-8",
    )

    evidence = collect_npm_evidence(tmp_path, "jspdf", "yarn.lock")

    assert evidence.package_manager == "yarn-classic"
    assert evidence.lockfile_version == "1"
    assert evidence.lockfile_path == "yarn.lock"
    assert evidence.proof_capabilities == ("resolved_instances",)
    assert evidence.completeness == "partial"
    assert [(instance.version, instance.relationship) for instance in evidence.instances] == [
        ("2.5.1", "direct")
    ]


def test_yarn_classic_records_transitive_consumers_and_shared_selectors(
    tmp_path: Path,
) -> None:
    (tmp_path / "package.json").write_text(
        json.dumps({"dependencies": {"parent": "1.0.0"}}),
        encoding="utf-8",
    )
    (tmp_path / "yarn.lock").write_text(
        """# yarn lockfile v1

parent@1.0.0:
  version "1.0.0"
  resolved "https://registry.yarnpkg.com/parent/-/parent-1.0.0.tgz"
  dependencies:
    target "^2.0.0"

target@^2.0.0, target@^2.1.0:
  version "2.1.0"
  resolved "https://registry.yarnpkg.com/target/-/target-2.1.0.tgz"
""",
        encoding="utf-8",
    )

    evidence = collect_npm_evidence(tmp_path, "target", "yarn.lock")

    assert len(evidence.instances) == 1
    assert evidence.instances[0].relationship == "transitive"
    assert evidence.dependency_consumers == ("yarn:parent@1.0.0:0",)


def test_yarn_classic_rejects_conflicts_and_unknown_versions(tmp_path: Path) -> None:
    (tmp_path / "package.json").write_text("{}", encoding="utf-8")
    for content in (
        "# yarn lockfile v2\n",
        "# yarn lockfile v1\n<<<<<<< HEAD\n",
    ):
        (tmp_path / "yarn.lock").write_text(content, encoding="utf-8")
        with pytest.raises(ValueError):
            collect_npm_evidence(tmp_path, "target", "yarn.lock")


@pytest.mark.parametrize(
    "resolved",
    (
        "",
        '  resolved "git+https://github.com/example/target.git"',
        '  resolved "https://example.com/target-1.0.0.tgz"',
    ),
)
def test_yarn_classic_requires_registry_backed_instances(
    resolved: str,
    tmp_path: Path,
) -> None:
    (tmp_path / "package.json").write_text(
        json.dumps({"dependencies": {"target": "1.0.0"}}),
        encoding="utf-8",
    )
    (tmp_path / "yarn.lock").write_text(
        f"""# yarn lockfile v1

target@1.0.0:
  version "1.0.0"
{resolved}
""",
        encoding="utf-8",
    )

    evidence = collect_npm_evidence(tmp_path, "target", "yarn.lock")

    assert len(evidence.instances) == 1
    assert not evidence.instances[0].comparable
    assert evidence.proof_capabilities == ()


def test_pnpm_v9_instances_and_consumers_are_positive_partial_evidence(
    tmp_path: Path,
) -> None:
    (tmp_path / "package.json").write_text(
        json.dumps({"dependencies": {"parent": "1.0.0"}}),
        encoding="utf-8",
    )
    (tmp_path / "pnpm-lock.yaml").write_text(
        """lockfileVersion: '9.0'
importers:
  .:
    dependencies:
      parent:
        specifier: 1.0.0
        version: 1.0.0
packages:
  parent@1.0.0:
    resolution: {integrity: sha512-parent}
  target@1.1.16:
    resolution: {integrity: sha512-target-one}
  target@2.1.2:
    resolution: {integrity: sha512-target-two}
snapshots:
  parent@1.0.0:
    dependencies:
      target: 1.1.16
  target@1.1.16: {}
  target@2.1.2: {}
""",
        encoding="utf-8",
    )

    evidence = collect_npm_evidence(tmp_path, "target", "pnpm-lock.yaml")

    assert evidence.package_manager == "pnpm"
    assert evidence.lockfile_version == "9.0"
    assert evidence.lockfile_path == "pnpm-lock.yaml"
    assert evidence.proof_capabilities == ("resolved_instances",)
    assert evidence.completeness == "partial"
    assert {instance.version for instance in evidence.instances} == {"1.1.16"}
    assert evidence.dependency_consumers == ("pnpm:parent@1.0.0",)
    assert any("unreferenced target instance" in issue for issue in evidence.issues)


def test_pnpm_v9_resolves_peer_suffixed_dependency_values(tmp_path: Path) -> None:
    (tmp_path / "package.json").write_text(
        json.dumps({"dependencies": {"parent": "1.0.0"}}),
        encoding="utf-8",
    )
    (tmp_path / "pnpm-lock.yaml").write_text(
        """lockfileVersion: '9.0'
importers:
  .:
    dependencies:
      parent:
        specifier: 1.0.0
        version: 1.0.0
packages:
  parent@1.0.0:
    resolution: {integrity: sha512-parent}
  target@2.0.0:
    resolution: {integrity: sha512-target}
snapshots:
  parent@1.0.0:
    dependencies:
      target: 2.0.0(peer@1.0.0)
  target@2.0.0(peer@1.0.0): {}
""",
        encoding="utf-8",
    )

    evidence = collect_npm_evidence(tmp_path, "target", "pnpm-lock.yaml")

    assert evidence.dependency_consumers == ("pnpm:parent@1.0.0",)
    assert not any("unresolved target dependency edge" in issue for issue in evidence.issues)


@pytest.mark.parametrize("version", ("workspace:*", "file:../target", "github:user/repo"))
def test_pnpm_v9_non_registry_versions_are_not_comparable(
    version: str,
    tmp_path: Path,
) -> None:
    (tmp_path / "package.json").write_text("{}", encoding="utf-8")
    (tmp_path / "pnpm-lock.yaml").write_text(
        f"""lockfileVersion: '9.0'
importers: {{'.': {{}}}}
packages:
  target@{version}:
    resolution: {{integrity: sha512-target}}
snapshots: {{}}
""",
        encoding="utf-8",
    )

    evidence = collect_npm_evidence(tmp_path, "target", "pnpm-lock.yaml")

    assert evidence.proof_capabilities == ()
    assert all(not instance.comparable for instance in evidence.instances)


@pytest.mark.parametrize(
    "resolution",
    (
        "{}",
        "{directory: ../target}",
        "{tarball: https://example.com/target-1.0.0.tgz}",
    ),
)
def test_pnpm_v9_requires_registry_resolution(
    resolution: str,
    tmp_path: Path,
) -> None:
    (tmp_path / "package.json").write_text(
        json.dumps({"dependencies": {"target": "1.0.0"}}),
        encoding="utf-8",
    )
    (tmp_path / "pnpm-lock.yaml").write_text(
        f"""lockfileVersion: '9.0'
importers:
  .:
    dependencies:
      target:
        specifier: 1.0.0
        version: 1.0.0
packages:
  target@1.0.0:
    resolution: {resolution}
snapshots:
  target@1.0.0: {{}}
""",
        encoding="utf-8",
    )

    evidence = collect_npm_evidence(tmp_path, "target", "pnpm-lock.yaml")

    assert len(evidence.instances) == 1
    assert not evidence.instances[0].comparable
    assert evidence.proof_capabilities == ()


@pytest.mark.parametrize(
    "malicious",
    (
        "lockfileVersion: '9.0'\npackages: &packages {}\nsnapshots: *packages\n",
        "lockfileVersion: '9.0'\npackages: {}\npackages: {}\n",
        "lockfileVersion: '9.0'\nvalue: !custom tagged\n",
    ),
)
def test_pnpm_rejects_yaml_aliases_duplicates_and_tags(
    malicious: str,
    tmp_path: Path,
) -> None:
    (tmp_path / "package.json").write_text("{}", encoding="utf-8")
    (tmp_path / "pnpm-lock.yaml").write_text(malicious, encoding="utf-8")

    with pytest.raises(ValueError):
        collect_npm_evidence(tmp_path, "target", "pnpm-lock.yaml")


@pytest.mark.parametrize(
    "content",
    (
        "lockfileVersion: '9.evil'\n",
        "lockfileVersion: '9.1'\n",
        "lockfileVersion: '8.0'\n",
        "lockfileVersion: '9.0'\n---\nlockfileVersion: '9.0'\n",
    ),
)
def test_pnpm_rejects_unsupported_versions_and_multiple_documents(
    content: str,
    tmp_path: Path,
) -> None:
    (tmp_path / "package.json").write_text("{}", encoding="utf-8")
    (tmp_path / "pnpm-lock.yaml").write_text(content, encoding="utf-8")

    with pytest.raises(ValueError):
        collect_npm_evidence(tmp_path, "target", "pnpm-lock.yaml")


def test_orphan_lockfile_records_cannot_authorize_positive_evidence(tmp_path: Path) -> None:
    (tmp_path / "package.json").write_text("{}", encoding="utf-8")
    (tmp_path / "yarn.lock").write_text(
        """# yarn lockfile v1

target@1.0.0:
  version "1.0.0"
  resolved "https://registry.yarnpkg.com/target/-/target-1.0.0.tgz"
""",
        encoding="utf-8",
    )

    evidence = collect_npm_evidence(tmp_path, "target", "yarn.lock")

    assert evidence.instances == ()
    assert evidence.proof_capabilities == ()
    assert any("unreferenced target instance" in issue for issue in evidence.issues)


@pytest.mark.parametrize(
    "duplicate",
    (
        '  version "1.0.1"',
        '  resolved "https://registry.npmjs.org/target/-/target-1.0.0.tgz"',
        '  dependencies:\n    child "2.0.0"\n  dependencies:',
        '  dependencies:\n    child "2.0.0"\n    child "2.1.0"',
    ),
)
def test_yarn_classic_rejects_duplicate_fields(
    duplicate: str,
    tmp_path: Path,
) -> None:
    (tmp_path / "package.json").write_text("{}", encoding="utf-8")
    (tmp_path / "yarn.lock").write_text(
        f"""# yarn lockfile v1

target@1.0.0:
  version "1.0.0"
  resolved "https://registry.yarnpkg.com/target/-/target-1.0.0.tgz"
{duplicate}
""",
        encoding="utf-8",
    )

    with pytest.raises(ValueError, match="duplicate"):
        collect_npm_evidence(tmp_path, "target", "yarn.lock")


def test_package_manifest_rejects_ambiguous_sibling_lockfiles(tmp_path: Path) -> None:
    (tmp_path / "package.json").write_text("{}", encoding="utf-8")
    (tmp_path / "yarn.lock").write_text("# yarn lockfile v1\n", encoding="utf-8")
    (tmp_path / "pnpm-lock.yaml").write_text(
        "lockfileVersion: '9.0'\n",
        encoding="utf-8",
    )

    with pytest.raises(ValueError, match="multiple npm ecosystem lockfiles"):
        collect_npm_evidence(tmp_path, "target", "package.json")


@pytest.mark.parametrize(
    ("lockfile_name", "lockfile_content"),
    (
        (
            "yarn.lock",
            """# yarn lockfile v1

lodash@4.17.20:
  version "4.17.20"
  resolved "https://registry.yarnpkg.com/lodash/-/lodash-4.17.20.tgz"
""",
        ),
        (
            "pnpm-lock.yaml",
            """lockfileVersion: '9.0'
importers:
  .:
    dependencies:
      lodash:
        specifier: 4.17.20
        version: 4.17.20
packages:
  lodash@4.17.20:
    resolution: {integrity: sha512-lodash}
snapshots:
  lodash@4.17.20: {}
""",
        ),
    ),
)
async def test_positive_partial_lockfile_evidence_is_terminal_applies(
    lockfile_name: str,
    lockfile_content: str,
    tmp_path: Path,
) -> None:
    case = tmp_path / "case"
    shutil.copytree(CASES / "triage-absent", case)
    (case / "agent-response.json").unlink(missing_ok=True)
    repository = case / "repository"
    (repository / "package-lock.json").unlink()
    (repository / "package.json").write_text(
        json.dumps({"dependencies": {"lodash": "4.17.20"}}),
        encoding="utf-8",
    )
    (repository / lockfile_name).write_text(lockfile_content, encoding="utf-8")
    alert = json.loads((case / "alert.json").read_text(encoding="utf-8"))
    alert["manifest_path"] = lockfile_name
    (case / "alert.json").write_text(json.dumps(alert), encoding="utf-8")

    output = await triage_offline_fixture(case, tmp_path / "out")
    report = json.loads((output / "report.json").read_text(encoding="utf-8"))
    result = report["result"]

    assert report["model_identity"] == "not_run"
    assert result["assessment"] == "applies"
    assert result["recommended_action"] == "remediate"
    assert result["reason_code"] == "triage_vulnerable_applies"
    assert not list(output.glob("agent-*.json"))
    assert not (output / "judge-review.json").exists()


@pytest.mark.parametrize("lockfile_name", ("yarn.lock", "pnpm-lock.yaml"))
async def test_partial_lockfile_absence_cannot_become_non_applicable(
    lockfile_name: str,
    tmp_path: Path,
) -> None:
    case = tmp_path / "case"
    shutil.copytree(CASES / "triage-absent", case)
    repository = case / "repository"
    (repository / "package-lock.json").unlink()
    (repository / lockfile_name).write_text(
        "# yarn lockfile v1\n"
        if lockfile_name == "yarn.lock"
        else "lockfileVersion: '9.0'\nimporters: {'.': {}}\npackages: {}\nsnapshots: {}\n",
        encoding="utf-8",
    )
    alert = json.loads((case / "alert.json").read_text(encoding="utf-8"))
    alert["manifest_path"] = lockfile_name
    (case / "alert.json").write_text(json.dumps(alert), encoding="utf-8")

    with pytest.raises(WorkflowError) as raised:
        await triage_offline_fixture(case, tmp_path / "out")

    assert raised.value.exit_code == 2
    decisions = list((tmp_path / "out").rglob("deterministic-decision.json"))
    assert len(decisions) == 1
    result = json.loads(decisions[0].read_text(encoding="utf-8"))
    assert result["assessment"] == "human_review"


@pytest.mark.parametrize(
    ("case_name", "reason_code"),
    (
        ("triage-dev-only", "dev_only_scope"),
        ("triage-vulnerable", "vulnerable_symbol_unused"),
    ),
)
@pytest.mark.parametrize(
    ("lockfile_name", "lockfile_content"),
    (
        ("yarn.lock", "# yarn lockfile v1\n"),
        (
            "pnpm-lock.yaml",
            "lockfileVersion: '9.0'\nimporters: {'.': {}}\npackages: {}\nsnapshots: {}\n",
        ),
    ),
)
async def test_partial_lockfiles_cannot_authorize_agentic_negative_proofs(
    case_name: str,
    reason_code: str,
    lockfile_name: str,
    lockfile_content: str,
    tmp_path: Path,
) -> None:
    case = tmp_path / "case"
    shutil.copytree(CASES / case_name, case)
    repository = case / "repository"
    (repository / "package-lock.json").unlink()
    (repository / lockfile_name).write_text(lockfile_content, encoding="utf-8")
    alert = json.loads((case / "alert.json").read_text(encoding="utf-8"))
    alert["manifest_path"] = lockfile_name
    (case / "alert.json").write_text(json.dumps(alert), encoding="utf-8")
    response = {
        "tool_calls": [{"name": "search", "arguments": {"query": "lodash", "path": "."}}],
        "finding": {
            "workflow_mode": "$task.workflow_mode",
            "correlation_id": "$task.correlation_id",
            "repository_id": "$task.repository_id",
            "alert_number": "$task.alert_number",
            "request_id": "$task.request_id",
            "snapshot_id": "$task.snapshot_id",
            "policy_digest": "$task.policy_digest",
            "claim": "Repository evidence supports non-applicability.",
            "citations": "$observations",
            "uncertainty": "",
            "proposed_recommendation": "approve",
            "policy_reason_code": reason_code,
            "confidence": 0.95,
            "insufficient_context": False,
            "injection_detected": False,
        },
    }
    (case / "agent-response.json").write_text(json.dumps(response), encoding="utf-8")

    output = await triage_offline_fixture(case, tmp_path / "out")
    report = json.loads((output / "report.json").read_text(encoding="utf-8"))
    result = report["result"]

    assert result["assessment"] == "human_review"
    assert result["recommended_action"] == "investigate"
    assert result["reason_code"] == "insufficient_context"
